//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.06 at 04:41:19 AM EST 
//


package org.mesa.xml.b2mml;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MaterialTestSpecificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MaterialTestSpecificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.mesa.org/xml/B2MML-V0600}NameType"/>
 *         &lt;element name="Description" type="{http://www.mesa.org/xml/B2MML-V0600}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Version" type="{http://www.mesa.org/xml/B2MML-V0600}VersionType" minOccurs="0"/>
 *         &lt;element name="Location" type="{http://www.mesa.org/xml/B2MML-V0600}LocationType" minOccurs="0"/>
 *         &lt;element name="HierarchyScope" type="{http://www.mesa.org/xml/B2MML-V0600}HierarchyScopeType" minOccurs="0"/>
 *         &lt;element name="TestedMaterialClassProperty" type="{http://www.mesa.org/xml/B2MML-V0600}TestedMaterialClassPropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TestedMaterialDefinitionProperty" type="{http://www.mesa.org/xml/B2MML-V0600}TestedMaterialDefinitionPropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TestedMaterialLotProperty" type="{http://www.mesa.org/xml/B2MML-V0600}TestedMaterialLotPropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-V0600-AllExtensions}MaterialTestSpecification" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MaterialTestSpecificationType", propOrder = {
    "name",
    "description",
    "version",
    "location",
    "hierarchyScope",
    "testedMaterialClassProperty",
    "testedMaterialDefinitionProperty",
    "testedMaterialLotProperty"
})
public class MaterialTestSpecificationType
    implements Serializable
{

    @XmlElement(name = "Name", required = true)
    protected NameType name;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "Version")
    protected VersionType version;
    @XmlElement(name = "Location")
    protected LocationType location;
    @XmlElement(name = "HierarchyScope")
    protected HierarchyScopeType hierarchyScope;
    @XmlElement(name = "TestedMaterialClassProperty")
    protected List<TestedMaterialClassPropertyType> testedMaterialClassProperty;
    @XmlElement(name = "TestedMaterialDefinitionProperty")
    protected List<TestedMaterialDefinitionPropertyType> testedMaterialDefinitionProperty;
    @XmlElement(name = "TestedMaterialLotProperty")
    protected List<TestedMaterialLotPropertyType> testedMaterialLotProperty;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setName(NameType value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link VersionType }
     *     
     */
    public VersionType getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersionType }
     *     
     */
    public void setVersion(VersionType value) {
        this.version = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationType }
     *     
     */
    public LocationType getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationType }
     *     
     */
    public void setLocation(LocationType value) {
        this.location = value;
    }

    /**
     * Gets the value of the hierarchyScope property.
     * 
     * @return
     *     possible object is
     *     {@link HierarchyScopeType }
     *     
     */
    public HierarchyScopeType getHierarchyScope() {
        return hierarchyScope;
    }

    /**
     * Sets the value of the hierarchyScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link HierarchyScopeType }
     *     
     */
    public void setHierarchyScope(HierarchyScopeType value) {
        this.hierarchyScope = value;
    }

    /**
     * Gets the value of the testedMaterialClassProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testedMaterialClassProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestedMaterialClassProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestedMaterialClassPropertyType }
     * 
     * 
     */
    public List<TestedMaterialClassPropertyType> getTestedMaterialClassProperty() {
        if (testedMaterialClassProperty == null) {
            testedMaterialClassProperty = new ArrayList<TestedMaterialClassPropertyType>();
        }
        return this.testedMaterialClassProperty;
    }

    /**
     * Gets the value of the testedMaterialDefinitionProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testedMaterialDefinitionProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestedMaterialDefinitionProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestedMaterialDefinitionPropertyType }
     * 
     * 
     */
    public List<TestedMaterialDefinitionPropertyType> getTestedMaterialDefinitionProperty() {
        if (testedMaterialDefinitionProperty == null) {
            testedMaterialDefinitionProperty = new ArrayList<TestedMaterialDefinitionPropertyType>();
        }
        return this.testedMaterialDefinitionProperty;
    }

    /**
     * Gets the value of the testedMaterialLotProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testedMaterialLotProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestedMaterialLotProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestedMaterialLotPropertyType }
     * 
     * 
     */
    public List<TestedMaterialLotPropertyType> getTestedMaterialLotProperty() {
        if (testedMaterialLotProperty == null) {
            testedMaterialLotProperty = new ArrayList<TestedMaterialLotPropertyType>();
        }
        return this.testedMaterialLotProperty;
    }

}
