//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.06 at 04:41:41 AM EST 
//


package org.mesa.xml.b2mml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PhysicalAssetSegmentSpecificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PhysicalAssetSegmentSpecificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PhysicalAssetClassID" type="{http://www.mesa.org/xml/B2MML-V0600}PhysicalAssetClassIDType" minOccurs="0"/>
 *         &lt;element name="PhysicalAssetID" type="{http://www.mesa.org/xml/B2MML-V0600}PhysicalAssetIDType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.mesa.org/xml/B2MML-V0600}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PhysicalAssetUse" type="{http://www.mesa.org/xml/B2MML-V0600}CodeType" minOccurs="0"/>
 *         &lt;element name="Quantity" type="{http://www.mesa.org/xml/B2MML-V0600}QuantityValueType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PhysicalAssetSegmentSpecificationProperty" type="{http://www.mesa.org/xml/B2MML-V0600}PhysicalAssetSegmentSpecificationPropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-V0600-AllExtensions}PhysicalAssetSegmentSpecification" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhysicalAssetSegmentSpecificationType", propOrder = {
    "physicalAssetClassID",
    "physicalAssetID",
    "description",
    "physicalAssetUse",
    "quantity",
    "physicalAssetSegmentSpecificationProperty"
})
public class PhysicalAssetSegmentSpecificationType {

    @XmlElement(name = "PhysicalAssetClassID")
    protected PhysicalAssetClassIDType physicalAssetClassID;
    @XmlElement(name = "PhysicalAssetID")
    protected PhysicalAssetIDType physicalAssetID;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "PhysicalAssetUse")
    protected CodeType physicalAssetUse;
    @XmlElement(name = "Quantity")
    protected List<QuantityValueType> quantity;
    @XmlElement(name = "PhysicalAssetSegmentSpecificationProperty")
    protected List<PhysicalAssetSegmentSpecificationPropertyType> physicalAssetSegmentSpecificationProperty;

    /**
     * Gets the value of the physicalAssetClassID property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalAssetClassIDType }
     *     
     */
    public PhysicalAssetClassIDType getPhysicalAssetClassID() {
        return physicalAssetClassID;
    }

    /**
     * Sets the value of the physicalAssetClassID property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalAssetClassIDType }
     *     
     */
    public void setPhysicalAssetClassID(PhysicalAssetClassIDType value) {
        this.physicalAssetClassID = value;
    }

    /**
     * Gets the value of the physicalAssetID property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalAssetIDType }
     *     
     */
    public PhysicalAssetIDType getPhysicalAssetID() {
        return physicalAssetID;
    }

    /**
     * Sets the value of the physicalAssetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalAssetIDType }
     *     
     */
    public void setPhysicalAssetID(PhysicalAssetIDType value) {
        this.physicalAssetID = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the physicalAssetUse property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getPhysicalAssetUse() {
        return physicalAssetUse;
    }

    /**
     * Sets the value of the physicalAssetUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setPhysicalAssetUse(CodeType value) {
        this.physicalAssetUse = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the quantity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuantity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QuantityValueType }
     * 
     * 
     */
    public List<QuantityValueType> getQuantity() {
        if (quantity == null) {
            quantity = new ArrayList<QuantityValueType>();
        }
        return this.quantity;
    }

    /**
     * Gets the value of the physicalAssetSegmentSpecificationProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the physicalAssetSegmentSpecificationProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysicalAssetSegmentSpecificationProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhysicalAssetSegmentSpecificationPropertyType }
     * 
     * 
     */
    public List<PhysicalAssetSegmentSpecificationPropertyType> getPhysicalAssetSegmentSpecificationProperty() {
        if (physicalAssetSegmentSpecificationProperty == null) {
            physicalAssetSegmentSpecificationProperty = new ArrayList<PhysicalAssetSegmentSpecificationPropertyType>();
        }
        return this.physicalAssetSegmentSpecificationProperty;
    }

}
