//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.06 at 04:41:39 AM EST 
//


package org.mesa.xml.b2mml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PhysicalAssetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PhysicalAssetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType"/>
 *         &lt;element name="Description" type="{http://www.mesa.org/xml/B2MML-V0600}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="HierarchyScope" type="{http://www.mesa.org/xml/B2MML-V0600}HierarchyScopeType" minOccurs="0"/>
 *         &lt;element name="PhysicalLocation" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="FixedAssetID" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="VendorID" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="EquipmentLevel" type="{http://www.mesa.org/xml/B2MML-V0600}HierarchyScopeType" minOccurs="0"/>
 *         &lt;element name="EquipmentAssetMapping" type="{http://www.mesa.org/xml/B2MML-V0600}EquipmentAssetMappingType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PhysicalAssetProperty" type="{http://www.mesa.org/xml/B2MML-V0600}PhysicalAssetPropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PhysicalAsset" type="{http://www.mesa.org/xml/B2MML-V0600}PhysicalAssetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PhysicalAssetClassID" type="{http://www.mesa.org/xml/B2MML-V0600}PhysicalAssetClassIDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PhysicalAssetCapabilityTestSpecificationID" type="{http://www.mesa.org/xml/B2MML-V0600}PhysicalAssetCapabilityTestSpecificationIDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-V0600-AllExtensions}PhysicalAsset" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhysicalAssetType", propOrder = {
    "id",
    "description",
    "hierarchyScope",
    "physicalLocation",
    "fixedAssetID",
    "vendorID",
    "equipmentLevel",
    "equipmentAssetMapping",
    "physicalAssetProperty",
    "physicalAsset",
    "physicalAssetClassID",
    "physicalAssetCapabilityTestSpecificationID"
})
public class PhysicalAssetType {

    @XmlElement(name = "ID", required = true)
    protected IdentifierType id;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "HierarchyScope")
    protected HierarchyScopeType hierarchyScope;
    @XmlElement(name = "PhysicalLocation")
    protected IdentifierType physicalLocation;
    @XmlElement(name = "FixedAssetID")
    protected IdentifierType fixedAssetID;
    @XmlElement(name = "VendorID")
    protected IdentifierType vendorID;
    @XmlElement(name = "EquipmentLevel")
    protected HierarchyScopeType equipmentLevel;
    @XmlElement(name = "EquipmentAssetMapping")
    protected List<EquipmentAssetMappingType> equipmentAssetMapping;
    @XmlElement(name = "PhysicalAssetProperty")
    protected List<PhysicalAssetPropertyType> physicalAssetProperty;
    @XmlElement(name = "PhysicalAsset")
    protected List<PhysicalAssetType> physicalAsset;
    @XmlElement(name = "PhysicalAssetClassID")
    protected List<PhysicalAssetClassIDType> physicalAssetClassID;
    @XmlElement(name = "PhysicalAssetCapabilityTestSpecificationID")
    protected List<PhysicalAssetCapabilityTestSpecificationIDType> physicalAssetCapabilityTestSpecificationID;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setID(IdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the hierarchyScope property.
     * 
     * @return
     *     possible object is
     *     {@link HierarchyScopeType }
     *     
     */
    public HierarchyScopeType getHierarchyScope() {
        return hierarchyScope;
    }

    /**
     * Sets the value of the hierarchyScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link HierarchyScopeType }
     *     
     */
    public void setHierarchyScope(HierarchyScopeType value) {
        this.hierarchyScope = value;
    }

    /**
     * Gets the value of the physicalLocation property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getPhysicalLocation() {
        return physicalLocation;
    }

    /**
     * Sets the value of the physicalLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setPhysicalLocation(IdentifierType value) {
        this.physicalLocation = value;
    }

    /**
     * Gets the value of the fixedAssetID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getFixedAssetID() {
        return fixedAssetID;
    }

    /**
     * Sets the value of the fixedAssetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setFixedAssetID(IdentifierType value) {
        this.fixedAssetID = value;
    }

    /**
     * Gets the value of the vendorID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getVendorID() {
        return vendorID;
    }

    /**
     * Sets the value of the vendorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setVendorID(IdentifierType value) {
        this.vendorID = value;
    }

    /**
     * Gets the value of the equipmentLevel property.
     * 
     * @return
     *     possible object is
     *     {@link HierarchyScopeType }
     *     
     */
    public HierarchyScopeType getEquipmentLevel() {
        return equipmentLevel;
    }

    /**
     * Sets the value of the equipmentLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link HierarchyScopeType }
     *     
     */
    public void setEquipmentLevel(HierarchyScopeType value) {
        this.equipmentLevel = value;
    }

    /**
     * Gets the value of the equipmentAssetMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipmentAssetMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipmentAssetMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EquipmentAssetMappingType }
     * 
     * 
     */
    public List<EquipmentAssetMappingType> getEquipmentAssetMapping() {
        if (equipmentAssetMapping == null) {
            equipmentAssetMapping = new ArrayList<EquipmentAssetMappingType>();
        }
        return this.equipmentAssetMapping;
    }

    /**
     * Gets the value of the physicalAssetProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the physicalAssetProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysicalAssetProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhysicalAssetPropertyType }
     * 
     * 
     */
    public List<PhysicalAssetPropertyType> getPhysicalAssetProperty() {
        if (physicalAssetProperty == null) {
            physicalAssetProperty = new ArrayList<PhysicalAssetPropertyType>();
        }
        return this.physicalAssetProperty;
    }

    /**
     * Gets the value of the physicalAsset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the physicalAsset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysicalAsset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhysicalAssetType }
     * 
     * 
     */
    public List<PhysicalAssetType> getPhysicalAsset() {
        if (physicalAsset == null) {
            physicalAsset = new ArrayList<PhysicalAssetType>();
        }
        return this.physicalAsset;
    }

    /**
     * Gets the value of the physicalAssetClassID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the physicalAssetClassID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysicalAssetClassID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhysicalAssetClassIDType }
     * 
     * 
     */
    public List<PhysicalAssetClassIDType> getPhysicalAssetClassID() {
        if (physicalAssetClassID == null) {
            physicalAssetClassID = new ArrayList<PhysicalAssetClassIDType>();
        }
        return this.physicalAssetClassID;
    }

    /**
     * Gets the value of the physicalAssetCapabilityTestSpecificationID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the physicalAssetCapabilityTestSpecificationID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysicalAssetCapabilityTestSpecificationID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhysicalAssetCapabilityTestSpecificationIDType }
     * 
     * 
     */
    public List<PhysicalAssetCapabilityTestSpecificationIDType> getPhysicalAssetCapabilityTestSpecificationID() {
        if (physicalAssetCapabilityTestSpecificationID == null) {
            physicalAssetCapabilityTestSpecificationID = new ArrayList<PhysicalAssetCapabilityTestSpecificationIDType>();
        }
        return this.physicalAssetCapabilityTestSpecificationID;
    }

}
