//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.06 at 04:41:41 AM EST 
//


package org.mesa.xml.b2mml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for ProcessSegmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessSegmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType"/>
 *         &lt;element name="Description" type="{http://www.mesa.org/xml/B2MML-V0600}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OperationsType" type="{http://www.mesa.org/xml/B2MML-V0600}OperationsTypeType" minOccurs="0"/>
 *         &lt;element name="Location" type="{http://www.mesa.org/xml/B2MML-V0600}LocationType" minOccurs="0"/>
 *         &lt;element name="HierarchyScope" type="{http://www.mesa.org/xml/B2MML-V0600}HierarchyScopeType" minOccurs="0"/>
 *         &lt;element name="PublishedDate" type="{http://www.mesa.org/xml/B2MML-V0600}PublishedDateType" minOccurs="0"/>
 *         &lt;element name="Duration" type="{http://www.mesa.org/xml/B2MML-V0600}DurationType" minOccurs="0"/>
 *         &lt;element name="PersonnelSegmentSpecification" type="{http://www.mesa.org/xml/B2MML-V0600}PersonnelSegmentSpecificationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EquipmentSegmentSpecification" type="{http://www.mesa.org/xml/B2MML-V0600}EquipmentSegmentSpecificationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PhysicalAssetSegmentSpecification" type="{http://www.mesa.org/xml/B2MML-V0600}PhysicalAssetSegmentSpecificationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MaterialSegmentSpecification" type="{http://www.mesa.org/xml/B2MML-V0600}MaterialSegmentSpecificationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Parameter" type="{http://www.mesa.org/xml/B2MML-V0600}ParameterType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SegmentDependency" type="{http://www.mesa.org/xml/B2MML-V0600}SegmentDependencyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ProcessSegment" type="{http://www.mesa.org/xml/B2MML-V0600}ProcessSegmentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-V0600-AllExtensions}ProcessSegment" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessSegmentType", propOrder = {
    "id",
    "description",
    "operationsType",
    "location",
    "hierarchyScope",
    "publishedDate",
    "duration",
    "personnelSegmentSpecification",
    "equipmentSegmentSpecification",
    "physicalAssetSegmentSpecification",
    "materialSegmentSpecification",
    "parameter",
    "segmentDependency",
    "processSegment"
})
public class ProcessSegmentType {

    @XmlElement(name = "ID", required = true)
    protected IdentifierType id;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "OperationsType")
    protected OperationsTypeType operationsType;
    @XmlElement(name = "Location")
    protected LocationType location;
    @XmlElement(name = "HierarchyScope")
    protected HierarchyScopeType hierarchyScope;
    @XmlElement(name = "PublishedDate")
    protected PublishedDateType publishedDate;
    @XmlElement(name = "Duration")
    protected Duration duration;
    @XmlElement(name = "PersonnelSegmentSpecification")
    protected List<PersonnelSegmentSpecificationType> personnelSegmentSpecification;
    @XmlElement(name = "EquipmentSegmentSpecification")
    protected List<EquipmentSegmentSpecificationType> equipmentSegmentSpecification;
    @XmlElement(name = "PhysicalAssetSegmentSpecification")
    protected List<PhysicalAssetSegmentSpecificationType> physicalAssetSegmentSpecification;
    @XmlElement(name = "MaterialSegmentSpecification")
    protected List<MaterialSegmentSpecificationType> materialSegmentSpecification;
    @XmlElement(name = "Parameter")
    protected List<ParameterType> parameter;
    @XmlElement(name = "SegmentDependency")
    protected List<SegmentDependencyType> segmentDependency;
    @XmlElement(name = "ProcessSegment")
    protected List<ProcessSegmentType> processSegment;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setID(IdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the operationsType property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsTypeType }
     *     
     */
    public OperationsTypeType getOperationsType() {
        return operationsType;
    }

    /**
     * Sets the value of the operationsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsTypeType }
     *     
     */
    public void setOperationsType(OperationsTypeType value) {
        this.operationsType = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationType }
     *     
     */
    public LocationType getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationType }
     *     
     */
    public void setLocation(LocationType value) {
        this.location = value;
    }

    /**
     * Gets the value of the hierarchyScope property.
     * 
     * @return
     *     possible object is
     *     {@link HierarchyScopeType }
     *     
     */
    public HierarchyScopeType getHierarchyScope() {
        return hierarchyScope;
    }

    /**
     * Sets the value of the hierarchyScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link HierarchyScopeType }
     *     
     */
    public void setHierarchyScope(HierarchyScopeType value) {
        this.hierarchyScope = value;
    }

    /**
     * Gets the value of the publishedDate property.
     * 
     * @return
     *     possible object is
     *     {@link PublishedDateType }
     *     
     */
    public PublishedDateType getPublishedDate() {
        return publishedDate;
    }

    /**
     * Sets the value of the publishedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublishedDateType }
     *     
     */
    public void setPublishedDate(PublishedDateType value) {
        this.publishedDate = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDuration(Duration value) {
        this.duration = value;
    }

    /**
     * Gets the value of the personnelSegmentSpecification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personnelSegmentSpecification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonnelSegmentSpecification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonnelSegmentSpecificationType }
     * 
     * 
     */
    public List<PersonnelSegmentSpecificationType> getPersonnelSegmentSpecification() {
        if (personnelSegmentSpecification == null) {
            personnelSegmentSpecification = new ArrayList<PersonnelSegmentSpecificationType>();
        }
        return this.personnelSegmentSpecification;
    }

    /**
     * Gets the value of the equipmentSegmentSpecification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipmentSegmentSpecification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipmentSegmentSpecification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EquipmentSegmentSpecificationType }
     * 
     * 
     */
    public List<EquipmentSegmentSpecificationType> getEquipmentSegmentSpecification() {
        if (equipmentSegmentSpecification == null) {
            equipmentSegmentSpecification = new ArrayList<EquipmentSegmentSpecificationType>();
        }
        return this.equipmentSegmentSpecification;
    }

    /**
     * Gets the value of the physicalAssetSegmentSpecification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the physicalAssetSegmentSpecification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysicalAssetSegmentSpecification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhysicalAssetSegmentSpecificationType }
     * 
     * 
     */
    public List<PhysicalAssetSegmentSpecificationType> getPhysicalAssetSegmentSpecification() {
        if (physicalAssetSegmentSpecification == null) {
            physicalAssetSegmentSpecification = new ArrayList<PhysicalAssetSegmentSpecificationType>();
        }
        return this.physicalAssetSegmentSpecification;
    }

    /**
     * Gets the value of the materialSegmentSpecification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the materialSegmentSpecification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaterialSegmentSpecification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MaterialSegmentSpecificationType }
     * 
     * 
     */
    public List<MaterialSegmentSpecificationType> getMaterialSegmentSpecification() {
        if (materialSegmentSpecification == null) {
            materialSegmentSpecification = new ArrayList<MaterialSegmentSpecificationType>();
        }
        return this.materialSegmentSpecification;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterType }
     * 
     * 
     */
    public List<ParameterType> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<ParameterType>();
        }
        return this.parameter;
    }

    /**
     * Gets the value of the segmentDependency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the segmentDependency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegmentDependency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SegmentDependencyType }
     * 
     * 
     */
    public List<SegmentDependencyType> getSegmentDependency() {
        if (segmentDependency == null) {
            segmentDependency = new ArrayList<SegmentDependencyType>();
        }
        return this.segmentDependency;
    }

    /**
     * Gets the value of the processSegment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processSegment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessSegment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessSegmentType }
     * 
     * 
     */
    public List<ProcessSegmentType> getProcessSegment() {
        if (processSegment == null) {
            processSegment = new ArrayList<ProcessSegmentType>();
        }
        return this.processSegment;
    }

}
