//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.06 at 04:41:57 AM EST 
//


package org.mesa.xml.b2mml;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResourceNetworkConnectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceNetworkConnectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.mesa.org/xml/B2MML-V0600}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ResourceNetworkConnectionID" type="{http://www.mesa.org/xml/B2MML-V0600}ResourceNetworkConnectionIDType" minOccurs="0"/>
 *         &lt;element name="FromResourceReference" type="{http://www.mesa.org/xml/B2MML-V0600}ResourceReferenceType"/>
 *         &lt;element name="ToResourceReference" type="{http://www.mesa.org/xml/B2MML-V0600}ResourceReferenceType"/>
 *         &lt;element name="ConnectionProperty" type="{http://www.mesa.org/xml/B2MML-V0600}ResourcePropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-V0600-AllExtensions}ResourceNetworkConnection" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceNetworkConnectionType", propOrder = {
    "id",
    "description",
    "resourceNetworkConnectionID",
    "fromResourceReference",
    "toResourceReference",
    "connectionProperty"
})
public class ResourceNetworkConnectionType
    implements Serializable
{

    @XmlElement(name = "ID")
    protected IdentifierType id;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "ResourceNetworkConnectionID")
    protected ResourceNetworkConnectionIDType resourceNetworkConnectionID;
    @XmlElement(name = "FromResourceReference", required = true)
    protected ResourceReferenceType fromResourceReference;
    @XmlElement(name = "ToResourceReference", required = true)
    protected ResourceReferenceType toResourceReference;
    @XmlElement(name = "ConnectionProperty")
    protected List<ResourcePropertyType> connectionProperty;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setID(IdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the resourceNetworkConnectionID property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceNetworkConnectionIDType }
     *     
     */
    public ResourceNetworkConnectionIDType getResourceNetworkConnectionID() {
        return resourceNetworkConnectionID;
    }

    /**
     * Sets the value of the resourceNetworkConnectionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceNetworkConnectionIDType }
     *     
     */
    public void setResourceNetworkConnectionID(ResourceNetworkConnectionIDType value) {
        this.resourceNetworkConnectionID = value;
    }

    /**
     * Gets the value of the fromResourceReference property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceReferenceType }
     *     
     */
    public ResourceReferenceType getFromResourceReference() {
        return fromResourceReference;
    }

    /**
     * Sets the value of the fromResourceReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceReferenceType }
     *     
     */
    public void setFromResourceReference(ResourceReferenceType value) {
        this.fromResourceReference = value;
    }

    /**
     * Gets the value of the toResourceReference property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceReferenceType }
     *     
     */
    public ResourceReferenceType getToResourceReference() {
        return toResourceReference;
    }

    /**
     * Sets the value of the toResourceReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceReferenceType }
     *     
     */
    public void setToResourceReference(ResourceReferenceType value) {
        this.toResourceReference = value;
    }

    /**
     * Gets the value of the connectionProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connectionProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnectionProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourcePropertyType }
     * 
     * 
     */
    public List<ResourcePropertyType> getConnectionProperty() {
        if (connectionProperty == null) {
            connectionProperty = new ArrayList<ResourcePropertyType>();
        }
        return this.connectionProperty;
    }

}
