//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.06 at 04:41:57 AM EST 
//


package org.mesa.xml.b2mml;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResourceReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="ResourceID" type="{http://www.mesa.org/xml/B2MML-V0600}ResourceIDType" minOccurs="0"/>
 *         &lt;element name="ResourceType" type="{http://www.mesa.org/xml/B2MML-V0600}ResourceReferenceTypeType" minOccurs="0"/>
 *         &lt;element name="ResourceProperty" type="{http://www.mesa.org/xml/B2MML-V0600}ResourcePropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-V0600-AllExtensions}ResourceReference" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceReferenceType", propOrder = {
    "id",
    "resourceID",
    "resourceType",
    "resourceProperty"
})
public class ResourceReferenceType
    implements Serializable
{

    @XmlElement(name = "ID")
    protected IdentifierType id;
    @XmlElement(name = "ResourceID")
    protected ResourceIDType resourceID;
    @XmlElement(name = "ResourceType")
    protected ResourceReferenceTypeType resourceType;
    @XmlElement(name = "ResourceProperty")
    protected List<ResourcePropertyType> resourceProperty;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setID(IdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the resourceID property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceIDType }
     *     
     */
    public ResourceIDType getResourceID() {
        return resourceID;
    }

    /**
     * Sets the value of the resourceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceIDType }
     *     
     */
    public void setResourceID(ResourceIDType value) {
        this.resourceID = value;
    }

    /**
     * Gets the value of the resourceType property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceReferenceTypeType }
     *     
     */
    public ResourceReferenceTypeType getResourceType() {
        return resourceType;
    }

    /**
     * Sets the value of the resourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceReferenceTypeType }
     *     
     */
    public void setResourceType(ResourceReferenceTypeType value) {
        this.resourceType = value;
    }

    /**
     * Gets the value of the resourceProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourcePropertyType }
     * 
     * 
     */
    public List<ResourcePropertyType> getResourceProperty() {
        if (resourceProperty == null) {
            resourceProperty = new ArrayList<ResourcePropertyType>();
        }
        return this.resourceProperty;
    }

}
