//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.06 at 04:41:59 AM EST 
//


package org.mesa.xml.b2mml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SupportedActionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SupportedActionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.mesa.org/xml/B2MML-V0600}IdentifierType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.mesa.org/xml/B2MML-V0600}DescriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TransactionVerb" type="{http://www.mesa.org/xml/B2MML-V0600}TransactionVerbType"/>
 *         &lt;element name="TransactionNoun" type="{http://www.mesa.org/xml/B2MML-V0600}TransactionNounType"/>
 *         &lt;element name="InformationUser" type="{http://www.mesa.org/xml/B2MML-V0600}IndicatorType" minOccurs="0"/>
 *         &lt;element name="InformationProvider" type="{http://www.mesa.org/xml/B2MML-V0600}IndicatorType" minOccurs="0"/>
 *         &lt;element name="InformationSender" type="{http://www.mesa.org/xml/B2MML-V0600}IndicatorType" minOccurs="0"/>
 *         &lt;element name="InformationReceiver" type="{http://www.mesa.org/xml/B2MML-V0600}IndicatorType" minOccurs="0"/>
 *         &lt;element name="ObjectWildcardSupported" type="{http://www.mesa.org/xml/B2MML-V0600}IndicatorType" minOccurs="0"/>
 *         &lt;element name="PropertyWildcardSupported" type="{http://www.mesa.org/xml/B2MML-V0600}IndicatorType" minOccurs="0"/>
 *         &lt;group ref="{http://www.mesa.org/xml/B2MML-V0600-AllExtensions}SupportedAction" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="releaseID" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="versionID" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupportedActionType", propOrder = {
    "id",
    "description",
    "transactionVerb",
    "transactionNoun",
    "informationUser",
    "informationProvider",
    "informationSender",
    "informationReceiver",
    "objectWildcardSupported",
    "propertyWildcardSupported"
})
public class SupportedActionType {

    @XmlElement(name = "ID")
    protected IdentifierType id;
    @XmlElement(name = "Description")
    protected List<DescriptionType> description;
    @XmlElement(name = "TransactionVerb", required = true)
    protected TransactionVerbType transactionVerb;
    @XmlElement(name = "TransactionNoun", required = true)
    protected TransactionNounType transactionNoun;
    @XmlElement(name = "InformationUser")
    protected Boolean informationUser;
    @XmlElement(name = "InformationProvider")
    protected Boolean informationProvider;
    @XmlElement(name = "InformationSender")
    protected Boolean informationSender;
    @XmlElement(name = "InformationReceiver")
    protected Boolean informationReceiver;
    @XmlElement(name = "ObjectWildcardSupported")
    protected Boolean objectWildcardSupported;
    @XmlElement(name = "PropertyWildcardSupported")
    protected Boolean propertyWildcardSupported;
    @XmlAttribute(name = "releaseID", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String releaseID;
    @XmlAttribute(name = "versionID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String versionID;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setID(IdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the transactionVerb property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionVerbType }
     *     
     */
    public TransactionVerbType getTransactionVerb() {
        return transactionVerb;
    }

    /**
     * Sets the value of the transactionVerb property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionVerbType }
     *     
     */
    public void setTransactionVerb(TransactionVerbType value) {
        this.transactionVerb = value;
    }

    /**
     * Gets the value of the transactionNoun property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionNounType }
     *     
     */
    public TransactionNounType getTransactionNoun() {
        return transactionNoun;
    }

    /**
     * Sets the value of the transactionNoun property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionNounType }
     *     
     */
    public void setTransactionNoun(TransactionNounType value) {
        this.transactionNoun = value;
    }

    /**
     * Gets the value of the informationUser property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInformationUser() {
        return informationUser;
    }

    /**
     * Sets the value of the informationUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInformationUser(Boolean value) {
        this.informationUser = value;
    }

    /**
     * Gets the value of the informationProvider property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInformationProvider() {
        return informationProvider;
    }

    /**
     * Sets the value of the informationProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInformationProvider(Boolean value) {
        this.informationProvider = value;
    }

    /**
     * Gets the value of the informationSender property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInformationSender() {
        return informationSender;
    }

    /**
     * Sets the value of the informationSender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInformationSender(Boolean value) {
        this.informationSender = value;
    }

    /**
     * Gets the value of the informationReceiver property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInformationReceiver() {
        return informationReceiver;
    }

    /**
     * Sets the value of the informationReceiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInformationReceiver(Boolean value) {
        this.informationReceiver = value;
    }

    /**
     * Gets the value of the objectWildcardSupported property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isObjectWildcardSupported() {
        return objectWildcardSupported;
    }

    /**
     * Sets the value of the objectWildcardSupported property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setObjectWildcardSupported(Boolean value) {
        this.objectWildcardSupported = value;
    }

    /**
     * Gets the value of the propertyWildcardSupported property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPropertyWildcardSupported() {
        return propertyWildcardSupported;
    }

    /**
     * Sets the value of the propertyWildcardSupported property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPropertyWildcardSupported(Boolean value) {
        this.propertyWildcardSupported = value;
    }

    /**
     * Gets the value of the releaseID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleaseID() {
        return releaseID;
    }

    /**
     * Sets the value of the releaseID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleaseID(String value) {
        this.releaseID = value;
    }

    /**
     * Gets the value of the versionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionID() {
        return versionID;
    }

    /**
     * Sets the value of the versionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionID(String value) {
        this.versionID = value;
    }

}
